# Generated by Django 5.2.7 on 2025-11-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_first_name_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
