# Generated by Django 5.2.7 on 2025-11-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('unknown', 'Unknown Event'), ('created', 'Create Event'), ('viewed', 'View Event'), ('saved', 'Save or Update Event')], default='viewed', max_length=50),
        ),
    ]
